name: 実装依頼
description: 実装依頼用テンプレート
title: "[FEATURE] No."

body:
  - type: input
    id: title
    attributes:
      label: 概要
      description: 対応内容の簡単な説明を入力してください
      placeholder: 対応内容の簡単な説明
    validations:
      required: false
  
  - type: input
    id: ref-issue
    attributes:
      label: マージ先
      description: マージ先のIssue番号を入力してください
      placeholder: マージ先のIssue番号
      value: #
    validations:
      required: true

  - type: input
    id: ref-ticket
    attributes:
      label: backlog
      description: backlogのリンクを入力してください
      placeholder: backlogのリンク
    validations:
      required: true
