name: Label From Linked Issue

on:
  issues:
    types: [opened, edited]

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Extract issue links and get labels
      uses: actions/github-script@v6
      with:
        script: |
          const issue = context.payload.issue;
          const body = issue.body;

          // 正規表現を使って本文からissueリンクを抽出
          const issueLinks = [...body.matchAll(/#(\d+)/g)];
          if (issueLinks.length === 0) {
            return;
          }

          const labelsToAdd = new Set();
          
          // 各リンクされたissueのラベルを取得
          for (const link of issueLinks) {
            const linkedIssueNumber = link[1];
            const { data: linkedIssue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: linkedIssueNumber,
            });

            // すべてのラベルをセットに追加
            linkedIssue.labels.forEach(label => labelsToAdd.add(label.name));
          }

          // 現在のissueにラベルを追加
          if (labelsToAdd.size > 0) {
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: Array.from(labelsToAdd),
            });
          }
