name: Sync Issue Labels

on:
  issues:
    types: [opened, edited]

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHubトークンを環境変数として定義
      REPO: ${{ github.repository }}  # リポジトリ名を環境変数に保存
      ISSUE_NUMBER: ${{ github.event.issue.number }}  # 現在のIssue番号
      ISSUE_BODY: ${{ github.event.issue.body }}  # 現在のIssueの本文

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract linked issue
        id: extract_issue
        run: |
          # Issueの本文からリンクされたIssueの番号を抽出
          LINKED_ISSUE=$(echo "$ISSUE_BODY" | grep -oP '#\d+')
          echo "Linked issue: $LINKED_ISSUE"

          # もしリンクされたIssueが見つからない場合は終了
          if [ -z "$LINKED_ISSUE" ]; then
            echo "No linked issue found. Exiting..."
            exit 0
          fi

          # リンクされたIssue番号をEnvironment Fileに保存
          echo "linked_issue_number=${LINKED_ISSUE:1}" >> $GITHUB_ENV

      - name: Get linked issue labels
        id: get_labels
        run: |
          LINKED_ISSUE_NUMBER=${{ env.linked_issue_number }}
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$LINKED_ISSUE_NUMBER")

          # リンクされたIssueのラベルを抽出
          LABELS=$(echo "$RESPONSE" | jq -r '.labels[].name')
          echo "Labels: $LABELS"

          # ラベルが設定されていない場合は終了
          if [ -z "$LABELS" ]; then
            echo "No labels found for the linked issue. Exiting..."
            exit 0
          fi

          # ラベルリストをEnvironment Fileに出力
          echo "labels=$(echo $LABELS | jq -R . | jq -s .)" >> $GITHUB_ENV

      - name: Add labels to the current issue
        run: |
          LABELS=${{ env.labels }}
          ISSUE_NUMBER=${{ env.ISSUE_NUMBER }}

          # 現在のIssueにラベルを追加
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels \
            -d "{\"labels\": $LABELS}"
